apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "dash-chart.fullname" . }}-pvc
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
  volumeName: {{ template "dash-chart.fullname" . }}-pv